### ISSUE TITLE
Unmount is broken for scripts-original

### ISSUE THREAD

**Issue by benmoss** [pivotal/usb-login-scripts#12]
I followed the directions and now just get `Unmount failed for /Volumes/keys/usb-login-scripts/scripts-original` when I run the load script. This appears to be because the script wasn't updated for being called from the parent load script.

**Comment by davidje13** [comment]
Confirmed. Should be an easy fix.

**Comment by davidje13** [comment]
@benmoss if you do a `git pull` from the usb-login-scripts folder it should now be working.

Also if you have any idea how this sort of thing could be tested I'd like to know! This is the second silly issue to appear due to folders changing (scripts-autoexpire was trying to load keys from the wrong place)

**Comment by davidje13** [comment]
@benmoss is this resolved for you?

**Comment by benmoss** [comment]
Yup, I just tested it out and it works. Thanks!
